const MINIMUM_NUMBER_PEOPLE = 1;
const MAX_NUMBER_PEOPLE = 3;
const MINIMUM_NUMBER_DAYS = 1;
const MAX_NUMBER_DAYS = 3;

module.exports = { MINIMUM_NUMBER_PEOPLE, MAX_NUMBER_PEOPLE, MINIMUM_NUMBER_DAYS, MAX_NUMBER_DAYS};